apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: express-backend
  template:
    metadata:
      labels:
        app: express-backend
    spec:
      containers:
      - name: backend
        image: express-backend:1.0
        ports:
        - containerPort: 3000
